### ISSUE TITLE
shouldn't it be "pickle.loads(zlib.decompress(data))"?

### ISSUE THREAD

**Issue by rouniuyizu** [belepi93/Ape-X#1]
BTW, thought in using zmq indeed works nicely. 

https://github.com/belepi93/Ape-X/blob/f34ce3b2ec1d1b407c63add92b1b0709b9565c23/actor.py#L123

**Comment by belepi93** [comment]
Thanks for comment! I'm trying to fix memory issue which happens when I run training in multi-node situation(like 200 actors with AWS) so there will be many changes to this repository.
